### ISSUE TITLE
"pretrained weights for the backbone" link dead

### ISSUE THREAD

**Issue by hinmanj** [JerryX1110/Robust-Video-Object-Segmentation#3]
[resnet101-deeplabv3p](https://drive.google.com/file/d/1H3yUShfPqzxSt-nHJP-zYSbbu2o_RQQu/view)

above link in the README does not exist.

**Comment by JerryX1110** [comment]
I am sorry to say that the link is maintained by the user of other repos.  And I could not have access to this file right now the same as you. 

My suggestion is that you can search for the pre-trained weights of ResNet101 backbone in the official DeepLabV3+ repo (https://github.com/jfzhang95/pytorch-deeplab-xception). If you still could not find a pre-trained weight for the backbone, you can directly train the whole model from scratch because I empirically find that the pre-training will not make a big difference in the final performance.

**Comment by JerryX1110** [comment]
Update: The pre-trained weights can be downloaded in this repo: https://github.com/VainF/DeepLabV3Plus-Pytorch
